# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ac359b8ad101ccb48b6a1157db5231b663b136eea707139a0e6ab7cebd1e480310d34e86f90a82beab778596c9e902184037f1084b5bdf4f5e146b0ad6e98a

test:
  secret_key_base: 2c7c767c4ed49f40741c9df867a125008736c2302317fed83ef1043f6b08eb5b4053bb13542b10cdee235c6d58d931568de450571d700f4a900ed37260528e8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
